/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integral;

/**
 *
 * @author BABOSHITAS
 */
public class e2 extends javax.swing.JFrame {

    /**
     * Creates new form e2
     */
    public e2() {
        initComponents();
        this.setLocationRelativeTo(null); 
        RES.setVisible(false);
        RES2.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        E3 = new javax.swing.JButton();
        E33 = new javax.swing.JButton();
        E333 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        E4 = new javax.swing.JButton();
        E44 = new javax.swing.JButton();
        E444 = new javax.swing.JButton();
        RES = new javax.swing.JButton();
        RES2 = new javax.swing.JButton();
        btnREGRESA1 = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1240, 950));
        setMinimumSize(new java.awt.Dimension(1240, 950));
        setPreferredSize(new java.awt.Dimension(1240, 950));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EJERCICIO 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 24), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Resuelve la integral y elige la opción correcta.");

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/3.1.PNG"))); // NOI18N
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });

        E33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/3.2.PNG"))); // NOI18N
        E33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E33ActionPerformed(evt);
            }
        });

        E333.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/3.3.PNG"))); // NOI18N
        E333.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E333ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/3.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(E33, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(E333, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(E333, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(E33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(32, 24, 813, 371);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EJERCICIO 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 24), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/4.PNG"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setText("Resuelve la integral y elige la opción correcta.");

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/4.1.PNG"))); // NOI18N
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });

        E44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/4.2.PNG"))); // NOI18N
        E44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E44ActionPerformed(evt);
            }
        });

        E444.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/4.3.PNG"))); // NOI18N
        E444.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E444ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(E44, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(E444, javax.swing.GroupLayout.PREFERRED_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E44, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(E444, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(32, 410, 810, 363);

        RES.setText("VER RESPUESTA");
        RES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESActionPerformed(evt);
            }
        });
        getContentPane().add(RES);
        RES.setBounds(970, 250, 160, 60);

        RES2.setText("VER RESPUESTA");
        RES2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RES2ActionPerformed(evt);
            }
        });
        getContentPane().add(RES2);
        RES2.setBounds(970, 580, 160, 60);

        btnREGRESA1.setBackground(new java.awt.Color(255, 255, 255));
        btnREGRESA1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnREGRESA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setText("REGRESAR");
        btnREGRESA1.setContentAreaFilled(false);
        btnREGRESA1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnREGRESA1.setName(""); // NOI18N
        btnREGRESA1.setPreferredSize(new java.awt.Dimension(151, 171));
        btnREGRESA1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar2.png"))); // NOI18N
        btnREGRESA1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnREGRESA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGRESA1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnREGRESA1);
        btnREGRESA1.setBounds(20, 760, 350, 160);

        SALIR.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setText("SALIR");
        SALIR.setContentAreaFilled(false);
        SALIR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SALIR.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache2.png"))); // NOI18N
        SALIR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SALIR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR);
        SALIR.setBounds(950, 750, 200, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESActionPerformed

    private void RES2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RES2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RES2ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        E33.setEnabled(true);
        E333.setEnabled(true);
    }//GEN-LAST:event_E3ActionPerformed

    private void E33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E33ActionPerformed
        E3.setEnabled(true);
        E333.setEnabled(true);
    }//GEN-LAST:event_E33ActionPerformed

    private void E333ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E333ActionPerformed
        E3.setEnabled(true);
        E33.setEnabled(true);
    }//GEN-LAST:event_E333ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        E444.setEnabled(true);
        E44.setEnabled(true);
    }//GEN-LAST:event_E4ActionPerformed

    private void E44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E44ActionPerformed
        E4.setEnabled(true);
        E444.setEnabled(true);
    }//GEN-LAST:event_E44ActionPerformed

    private void E444ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E444ActionPerformed
        E4.setEnabled(true);
        E44.setEnabled(true);
    }//GEN-LAST:event_E444ActionPerformed

    private void btnREGRESA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGRESA1ActionPerformed
        menu abrir = new menu();
        abrir.setVisible(true); 
        dispose();
    }//GEN-LAST:event_btnREGRESA1ActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
       dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(e2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(e2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(e2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(e2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new e2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E3;
    private javax.swing.JButton E33;
    private javax.swing.JButton E333;
    private javax.swing.JButton E4;
    private javax.swing.JButton E44;
    private javax.swing.JButton E444;
    private javax.swing.JButton RES;
    private javax.swing.JButton RES2;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton btnREGRESA1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
