/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integral;

/**
 *
 * @author BABOSHITAS
 */
public class e5 extends javax.swing.JFrame {

    /**
     * Creates new form e5
     */
    public e5() {
        initComponents();
        this.setLocationRelativeTo(null); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        E9 = new javax.swing.JButton();
        E99 = new javax.swing.JButton();
        E999 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnE2 = new javax.swing.JButton();
        E12 = new javax.swing.JButton();
        btnE112 = new javax.swing.JButton();
        RES = new javax.swing.JButton();
        btnREGRESA1 = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1240, 950));
        setMinimumSize(new java.awt.Dimension(1240, 950));
        setPreferredSize(new java.awt.Dimension(1240, 950));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EJERCICIO 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 24), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/9.PNG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Resuelve la integral y elige la opción correcta.");

        E9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/9.1.PNG"))); // NOI18N

        E99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/9.2.PNG"))); // NOI18N

        E999.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/9.3.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(E9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(E99, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(E999, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(E99, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E999, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 30, 845, 350);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EJERCICIO 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 24), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Resuelve la integral y elige la opción correcta.");

        btnE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/7.1.PNG"))); // NOI18N

        E12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/7.2.PNG"))); // NOI18N

        btnE112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/7.3.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnE2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(E12, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnE112, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnE112, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(696, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 390, 840, 320);

        RES.setText("VER RESPUESTA");
        RES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESActionPerformed(evt);
            }
        });
        getContentPane().add(RES);
        RES.setBounds(1044, 300, 160, 60);

        btnREGRESA1.setBackground(new java.awt.Color(255, 255, 255));
        btnREGRESA1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnREGRESA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setText("REGRESAR");
        btnREGRESA1.setContentAreaFilled(false);
        btnREGRESA1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnREGRESA1.setName(""); // NOI18N
        btnREGRESA1.setPreferredSize(new java.awt.Dimension(151, 171));
        btnREGRESA1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar2.png"))); // NOI18N
        btnREGRESA1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnREGRESA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGRESA1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnREGRESA1);
        btnREGRESA1.setBounds(30, 730, 350, 160);

        SALIR.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setText("SALIR");
        SALIR.setContentAreaFilled(false);
        SALIR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SALIR.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache2.png"))); // NOI18N
        SALIR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SALIR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR);
        SALIR.setBounds(1020, 720, 200, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESActionPerformed

    private void btnREGRESA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGRESA1ActionPerformed
        menu abrir = new menu();
        abrir.setVisible(true); 
        dispose();
    }//GEN-LAST:event_btnREGRESA1ActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(e5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(e5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(e5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(e5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new e5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E12;
    private javax.swing.JButton E9;
    private javax.swing.JButton E99;
    private javax.swing.JButton E999;
    private javax.swing.JButton RES;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton btnE112;
    private javax.swing.JButton btnE2;
    private javax.swing.JButton btnREGRESA1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
