/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integral;

/**
 *
 * @author DONAS
 */
public class INICIO2 extends javax.swing.JFrame {

    /**
     * Creates new form INICIO2
     */
    public INICIO2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEJERCICIOS = new javax.swing.JButton();
        ESTRELLAS = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnREGRESA1 = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEJERCICIOS.setText("EJERCICIOS");
        btnEJERCICIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEJERCICIOSActionPerformed(evt);
            }
        });

        ESTRELLAS.setText("ESTRELLAS");

        jButton3.setText("JUEGOS");

        jButton4.setText("TUTORIALES");

        btnREGRESA1.setBackground(new java.awt.Color(255, 255, 255));
        btnREGRESA1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnREGRESA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setContentAreaFilled(false);
        btnREGRESA1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnREGRESA1.setName(""); // NOI18N
        btnREGRESA1.setPreferredSize(new java.awt.Dimension(151, 171));
        btnREGRESA1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar2.png"))); // NOI18N
        btnREGRESA1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnREGRESA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGRESA1ActionPerformed(evt);
            }
        });

        SALIR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setText("CERRAR SESIÒN");
        SALIR.setContentAreaFilled(false);
        SALIR.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SALIR.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache2.png"))); // NOI18N
        SALIR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnREGRESA1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEJERCICIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESTRELLAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SALIR)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEJERCICIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ESTRELLAS, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(btnREGRESA1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnREGRESA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGRESA1ActionPerformed
        menu abrir = new menu();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnREGRESA1ActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        INICIOUSUARIO iu = new INICIOUSUARIO();//
        iu.setVisible(true);
        dispose ();
    }//GEN-LAST:event_SALIRActionPerformed

    private void btnEJERCICIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEJERCICIOSActionPerformed
     menu abrir = new menu();
    abrir.setVisible(true); 
    dispose(); 
    }//GEN-LAST:event_btnEJERCICIOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ESTRELLAS;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton btnEJERCICIOS;
    private javax.swing.JButton btnREGRESA1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
