/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integral;

import java.awt.Color;

/**
 *
 * @author JHOVANY
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        jPanel1.setBackground(new Color (0,0,0,60) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btne1 = new javax.swing.JButton();
        btnej1 = new javax.swing.JButton();
        btne2 = new javax.swing.JButton();
        btnej2 = new javax.swing.JButton();
        btne4 = new javax.swing.JButton();
        btnej3 = new javax.swing.JButton();
        btne3 = new javax.swing.JButton();
        btnej4 = new javax.swing.JButton();
        btne5 = new javax.swing.JButton();
        btnej5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnej6 = new javax.swing.JButton();
        btne6 = new javax.swing.JButton();
        btnej7 = new javax.swing.JButton();
        btnej8 = new javax.swing.JButton();
        btnej9 = new javax.swing.JButton();
        btnej10 = new javax.swing.JButton();
        btne7 = new javax.swing.JButton();
        btne8 = new javax.swing.JButton();
        btne9 = new javax.swing.JButton();
        btne10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnej11 = new javax.swing.JButton();
        btne11 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnREGRESA1 = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1128, 740));
        setMinimumSize(new java.awt.Dimension(1128, 740));
        setPreferredSize(new java.awt.Dimension(1128, 740));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FÓRMULAS DE INTEGRALES INMEDIATAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 36), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f1.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f2.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f3.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f4.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f5.jpg"))); // NOI18N

        btne1.setText("ejercicios");
        btne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne1ActionPerformed(evt);
            }
        });

        btnej1.setText("ejemplo");
        btnej1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej1ActionPerformed(evt);
            }
        });

        btne2.setText("ejercicios");
        btne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne2ActionPerformed(evt);
            }
        });

        btnej2.setText("ejemplo");
        btnej2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej2ActionPerformed(evt);
            }
        });

        btne4.setText("ejercicios");
        btne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne4ActionPerformed(evt);
            }
        });

        btnej3.setText("ejemplo");
        btnej3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej3ActionPerformed(evt);
            }
        });

        btne3.setText("ejercicios");
        btne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne3ActionPerformed(evt);
            }
        });

        btnej4.setText("ejemplo");
        btnej4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej4ActionPerformed(evt);
            }
        });

        btne5.setText("ejercicos");
        btne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne5ActionPerformed(evt);
            }
        });

        btnej5.setText("ejemplo");
        btnej5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej5ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f6.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f7.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f8.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/f9.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/10.jpg"))); // NOI18N

        btnej6.setText("ejemplo");
        btnej6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej6ActionPerformed(evt);
            }
        });

        btne6.setText("ejercicios");
        btne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne6ActionPerformed(evt);
            }
        });

        btnej7.setText("ejemplo");
        btnej7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej7ActionPerformed(evt);
            }
        });

        btnej8.setText("ejemplo");
        btnej8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej8ActionPerformed(evt);
            }
        });

        btnej9.setText("ejemplo");
        btnej9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej9ActionPerformed(evt);
            }
        });

        btnej10.setText("ejemplo");
        btnej10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej10ActionPerformed(evt);
            }
        });

        btne7.setText("ejercicios");
        btne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne7ActionPerformed(evt);
            }
        });

        btne8.setText("ejercicios");
        btne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne8ActionPerformed(evt);
            }
        });

        btne9.setText("ejercicios");
        btne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne9ActionPerformed(evt);
            }
        });

        btne10.setText("ejercicios");
        btne10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne10ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/11.jpg"))); // NOI18N

        btnej11.setText("ejemplo");
        btnej11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej11ActionPerformed(evt);
            }
        });

        btne11.setText("ejercicios");
        btne11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnej1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btne1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnej3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btne2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnej2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btne4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnej4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnej5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btne3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btne5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btne11)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnej8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnej10)
                                    .addComponent(btnej9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnej7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnej11)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btne10)
                                    .addComponent(btne9)
                                    .addComponent(btne8)
                                    .addComponent(btne7)
                                    .addComponent(btne6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnej6)))
                        .addGap(179, 179, 179))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnej1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btne1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnej9)
                        .addGap(366, 366, 366))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnej3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btne2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btne3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btne5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnej6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(96, 96, 96))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnej8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btne8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnej10)
                        .addComponent(btne9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnej7)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btne10)
                                .addGap(39, 39, 39)
                                .addComponent(btne7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnej11)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(btne6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnej2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btne4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btne11)
                                .addComponent(btnej4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnej5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(188, 188, 188))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 1066, 510);
        jPanel1.getAccessibleContext().setAccessibleName("FÒRMULAS DE INTEGRALES INMEDIATAS");

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechas.png"))); // NOI18N
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechas2.png"))); // NOI18N
        btnSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechas.png"))); // NOI18N
        btnSiguiente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechas2.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(910, 570, 161, 100);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/1600x900_rustic-autumn.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1110, 560);

        btnREGRESA1.setBackground(new java.awt.Color(255, 255, 255));
        btnREGRESA1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnREGRESA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setContentAreaFilled(false);
        btnREGRESA1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnREGRESA1.setName(""); // NOI18N
        btnREGRESA1.setPreferredSize(new java.awt.Dimension(151, 171));
        btnREGRESA1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar2.png"))); // NOI18N
        btnREGRESA1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/flechar.png"))); // NOI18N
        btnREGRESA1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnREGRESA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGRESA1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnREGRESA1);
        btnREGRESA1.setBounds(40, 580, 190, 116);

        SALIR.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setContentAreaFilled(false);
        SALIR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SALIR.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache2.png"))); // NOI18N
        SALIR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/tache.png"))); // NOI18N
        SALIR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        SALIR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR);
        SALIR.setBounds(470, 590, 160, 80);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicios/t2.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 560, 1110, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
     menu2 abrir = new menu2();
     abrir.setVisible(true);
     dispose ();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btne11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne11ActionPerformed
        e11 ejercicio11 = new e11();//
        ejercicio11.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne11ActionPerformed

    private void btnej11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej11ActionPerformed
        ej11 ejemplo11 = new ej11();//
        ejemplo11.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej11ActionPerformed

    private void btne10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne10ActionPerformed
        e10 ejercicio10 = new e10();//
        ejercicio10.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne10ActionPerformed

    private void btne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne9ActionPerformed
        e9 ejercicio9 = new e9();//
        ejercicio9.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne9ActionPerformed

    private void btne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne8ActionPerformed
        e8 ejercicio8 = new e8();//
        ejercicio8.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne8ActionPerformed

    private void btne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne7ActionPerformed
        e7 ejercicio7 = new e7();//
        ejercicio7.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne7ActionPerformed

    private void btnej10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej10ActionPerformed
        ej10 ejemplo10 = new ej10();//
        ejemplo10.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej10ActionPerformed

    private void btnej9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej9ActionPerformed
        ej9 ejemplo9 = new ej9();//
        ejemplo9.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej9ActionPerformed

    private void btnej8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej8ActionPerformed
        ej8 ejemplo8 = new ej8();//
        ejemplo8.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej8ActionPerformed

    private void btnej7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej7ActionPerformed
        ej7 ejemplo7 = new ej7();//
        ejemplo7.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej7ActionPerformed

    private void btne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne6ActionPerformed
        e6 ejercicio6 = new e6();//
        ejercicio6.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne6ActionPerformed

    private void btnej6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej6ActionPerformed
        ej6 ejemplo6 = new ej6();//
        ejemplo6.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej6ActionPerformed

    private void btnej5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej5ActionPerformed
        ej5 ejemplo5 = new ej5();//
        ejemplo5.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej5ActionPerformed

    private void btne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne5ActionPerformed
        e5 ejercicio5 = new e5();//
        ejercicio5.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne5ActionPerformed

    private void btnej4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej4ActionPerformed
        ej4 ejemplo4 = new ej4();//
        ejemplo4.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej4ActionPerformed

    private void btne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne3ActionPerformed
        e3 ejercicio3 = new e3();//
        ejercicio3.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne3ActionPerformed

    private void btnej3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej3ActionPerformed
        ej3 ejemplo3 = new ej3();//
        ejemplo3.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej3ActionPerformed

    private void btne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne4ActionPerformed
        e4 ejercicio4 = new e4();//
        ejercicio4.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne4ActionPerformed

    private void btnej2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej2ActionPerformed
        ej2 ejemplo2 = new ej2(); //
        ejemplo2.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej2ActionPerformed

    private void btne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne2ActionPerformed
        e2 ejercicio2 = new e2();//
        ejercicio2.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne2ActionPerformed

    private void btnej1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej1ActionPerformed
        ej1 ejemplo1 = new ej1();//
        ejemplo1.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnej1ActionPerformed

    private void btne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne1ActionPerformed
        e1 ejercicio1 = new e1();//
        ejercicio1.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btne1ActionPerformed

    private void btnREGRESA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGRESA1ActionPerformed
        INICIO2 i2 = new INICIO2();//
        i2.setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnREGRESA1ActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SALIR;
    private javax.swing.JButton btnREGRESA1;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btne1;
    private javax.swing.JButton btne10;
    private javax.swing.JButton btne11;
    private javax.swing.JButton btne2;
    private javax.swing.JButton btne3;
    private javax.swing.JButton btne4;
    private javax.swing.JButton btne5;
    private javax.swing.JButton btne6;
    private javax.swing.JButton btne7;
    private javax.swing.JButton btne8;
    private javax.swing.JButton btne9;
    private javax.swing.JButton btnej1;
    private javax.swing.JButton btnej10;
    private javax.swing.JButton btnej11;
    private javax.swing.JButton btnej2;
    private javax.swing.JButton btnej3;
    private javax.swing.JButton btnej4;
    private javax.swing.JButton btnej5;
    private javax.swing.JButton btnej6;
    private javax.swing.JButton btnej7;
    private javax.swing.JButton btnej8;
    private javax.swing.JButton btnej9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
