/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integral;

/**
 *
 * @author JHOVANY
 */
public class menu2 extends javax.swing.JFrame {

    /**
     * Creates new form menu2
     */
    public menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btne12 = new javax.swing.JButton();
        btnej12 = new javax.swing.JButton();
        btne13 = new javax.swing.JButton();
        btnej13 = new javax.swing.JButton();
        btne15 = new javax.swing.JButton();
        btnej14 = new javax.swing.JButton();
        btne14 = new javax.swing.JButton();
        btnej15 = new javax.swing.JButton();
        btne16 = new javax.swing.JButton();
        btnej16 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnej17 = new javax.swing.JButton();
        btne17 = new javax.swing.JButton();
        btnej18 = new javax.swing.JButton();
        btnej19 = new javax.swing.JButton();
        btnej20 = new javax.swing.JButton();
        btnej21 = new javax.swing.JButton();
        btne18 = new javax.swing.JButton();
        btne19 = new javax.swing.JButton();
        btne20 = new javax.swing.JButton();
        btne21 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnej22 = new javax.swing.JButton();
        btne22 = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "formulas de integrales inmediatas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/12.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/13.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/14.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/15.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/16.jpg"))); // NOI18N

        btne12.setText("ejercicios");
        btne12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne12ActionPerformed(evt);
            }
        });

        btnej12.setText("ejemplo");
        btnej12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej12ActionPerformed(evt);
            }
        });

        btne13.setText("ejercicios");
        btne13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne13ActionPerformed(evt);
            }
        });

        btnej13.setText("ejemplo");
        btnej13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej13ActionPerformed(evt);
            }
        });

        btne15.setText("ejercicios");
        btne15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne15ActionPerformed(evt);
            }
        });

        btnej14.setText("ejemplo");
        btnej14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej14ActionPerformed(evt);
            }
        });

        btne14.setText("ejercicios");
        btne14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne14ActionPerformed(evt);
            }
        });

        btnej15.setText("ejemplo");
        btnej15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej15ActionPerformed(evt);
            }
        });

        btne16.setText("ejercicos");
        btne16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne16ActionPerformed(evt);
            }
        });

        btnej16.setText("ejemplo");
        btnej16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej16ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/17.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/18.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/19.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/20.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/21.jpg"))); // NOI18N

        btnej17.setText("ejemplo");
        btnej17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej17ActionPerformed(evt);
            }
        });

        btne17.setText("ejercicios");
        btne17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne17ActionPerformed(evt);
            }
        });

        btnej18.setText("ejemplo");
        btnej18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej18ActionPerformed(evt);
            }
        });

        btnej19.setText("ejemplo");
        btnej19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej19ActionPerformed(evt);
            }
        });

        btnej20.setText("ejemplo");
        btnej20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej20ActionPerformed(evt);
            }
        });

        btnej21.setText("ejemplo");
        btnej21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej21ActionPerformed(evt);
            }
        });

        btne18.setText("ejercicios");
        btne18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne18ActionPerformed(evt);
            }
        });

        btne19.setText("ejercicios");
        btne19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne19ActionPerformed(evt);
            }
        });

        btne20.setText("ejercicios");
        btne20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne20ActionPerformed(evt);
            }
        });

        btne21.setText("ejercicios");
        btne21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne21ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integral/formulas/integral/22.jpg"))); // NOI18N

        btnej22.setText("ejemplo");
        btnej22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnej22ActionPerformed(evt);
            }
        });

        btne22.setText("ejercicios");
        btne22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne22ActionPerformed(evt);
            }
        });

        btnAnterior.setText("anterior parte");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnej12)
                            .addComponent(btnej13)
                            .addComponent(btnej14)
                            .addComponent(btnej15)
                            .addComponent(btnej16))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btne15)
                            .addComponent(btne14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btne13)
                                            .addComponent(btne12))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(96, 96, 96)
                                                .addComponent(btnej17))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11))
                                                .addGap(72, 72, 72)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnej19)
                                                    .addComponent(btnej18)
                                                    .addComponent(btnej20)
                                                    .addComponent(btnej21)
                                                    .addComponent(btnej22)))))
                                    .addComponent(btne16))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btne18)
                                    .addComponent(btne17)
                                    .addComponent(btne19)
                                    .addComponent(btne20)
                                    .addComponent(btne21)
                                    .addComponent(btne22))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btne12)
                                .addComponent(btnej12))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnej17)
                                .addComponent(btne17)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnej13)
                                        .addComponent(btne13))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnej18)
                                    .addComponent(btne18))))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnej19)
                                    .addComponent(btne19)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnej14)
                            .addComponent(btne14))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnej15)
                                .addComponent(btne15))
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btne16)
                                .addComponent(btnej16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnterior)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnej20)
                                .addComponent(btne20))
                            .addComponent(jLabel9))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnej21)
                                .addComponent(btne21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnej22)
                                .addComponent(btne22)))
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnej12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej12ActionPerformed
     ej12 ejemplo12 = new ej12(); //
     ejemplo12.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej12ActionPerformed

    private void btnej13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej13ActionPerformed
    ej13 ejemplo13 = new ej13();//
     ejemplo13.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej13ActionPerformed

    private void btnej14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej14ActionPerformed
     ej14 ejemplo14 = new ej14(); //
     ejemplo14.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej14ActionPerformed

    private void btnej15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej15ActionPerformed
     ej15 ejemplo15 = new ej15(); //
     ejemplo15.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej15ActionPerformed

    private void btnej17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej17ActionPerformed
     ej17 ejemplo17 = new ej17();//
     ejemplo17.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej17ActionPerformed

    private void btne17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne17ActionPerformed
     e17 ejercicio17 = new e17();//
     ejercicio17.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne17ActionPerformed

    private void btnej19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej19ActionPerformed
      ej19 ejemplo19 = new ej19();//
     ejemplo19.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej19ActionPerformed

    private void btnej20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej20ActionPerformed
     ej20 ejemplo20 = new ej20();//
     ejemplo20.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej20ActionPerformed

    private void btnej21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej21ActionPerformed
      ej21 ejemplo21 = new ej21();//
     ejemplo21.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej21ActionPerformed

    private void btne18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne18ActionPerformed
     e18 ejercicio18 = new e18();//
     ejercicio18.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne18ActionPerformed

    private void btne19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne19ActionPerformed
     e19 ejercicio19 = new e19();//
     ejercicio19.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne19ActionPerformed

    private void btne20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne20ActionPerformed
     e20 ejercicio20 = new e20();//
     ejercicio20.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne20ActionPerformed

    private void btne21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne21ActionPerformed
     e21 ejercicio21 = new e21();//
     ejercicio21.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne21ActionPerformed

    private void btnej22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej22ActionPerformed
     ej22 ejemplo22 = new ej22();//
     ejemplo22.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej22ActionPerformed

    private void btne22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne22ActionPerformed
     e22 ejercicio22 = new e22();//
     ejercicio22.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne22ActionPerformed

    private void btnej18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej18ActionPerformed
     ej18 ejemplo18 = new ej18();
     ejemplo18.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej18ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
    menu abrir = new menu();
    abrir.setVisible(true); 
    dispose();     
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btne12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne12ActionPerformed
     e12 ejercicio12 = new e12();//
     ejercicio12.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne12ActionPerformed

    private void btnej16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnej16ActionPerformed
     ej16 ejemplo16 = new ej16();
     ejemplo16.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btnej16ActionPerformed

    private void btne13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne13ActionPerformed
        e13 ejercicio13 = new e13();//
     ejercicio13.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne13ActionPerformed

    private void btne14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne14ActionPerformed
         e14 ejercicio14 = new e14();//
     ejercicio14.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne14ActionPerformed

    private void btne15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne15ActionPerformed
         e15 ejercicio15 = new e15();//
     ejercicio15.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne15ActionPerformed

    private void btne16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne16ActionPerformed
         e16 ejercicio16= new e16();//
     ejercicio16.setVisible(true);
     dispose ();
    }//GEN-LAST:event_btne16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btne12;
    private javax.swing.JButton btne13;
    private javax.swing.JButton btne14;
    private javax.swing.JButton btne15;
    private javax.swing.JButton btne16;
    private javax.swing.JButton btne17;
    private javax.swing.JButton btne18;
    private javax.swing.JButton btne19;
    private javax.swing.JButton btne20;
    private javax.swing.JButton btne21;
    private javax.swing.JButton btne22;
    private javax.swing.JButton btnej12;
    private javax.swing.JButton btnej13;
    private javax.swing.JButton btnej14;
    private javax.swing.JButton btnej15;
    private javax.swing.JButton btnej16;
    private javax.swing.JButton btnej17;
    private javax.swing.JButton btnej18;
    private javax.swing.JButton btnej19;
    private javax.swing.JButton btnej20;
    private javax.swing.JButton btnej21;
    private javax.swing.JButton btnej22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
